function spm_petpve12
% Toolbox wrapper to call petpve functions
%_______________________________________________________________________
% Gabriel Gonzalez-Escamilla
% $Id: geg_PET_PVEc.m 001 2015-03-07 19:46:37Z GaBbo $
clc
rev = '$Rev: 010 $';

spm('FnBanner',mfilename,rev);
[~,Fgraph,~] = spm('FnUIsetup','PET-PVEcorrection toolbox');
spm_help('!Disp','PET-PVEc_12.man','',Fgraph,'PET Partial Volume Effects correction toolbox for SPM12');

% get current release number
A = ver;
for i=1:length(A)
    if strcmp(A(i).Name,'PET Partial Volume Effects correction Toolbox')
        r = str2double(A(i).Version);
    end
end
if exist('r','var')   
    disp( '   _____    _____  _______         _____  _  __  _____                                                 ')
    disp( '  / __  \  /  __/\/__  __/\ ___   / ___ \| |/ /\/  __/\                                                ')
    disp( ' / ,.___/,/  __/\/\_/ / _\//__/\ /  ,.__/|   / /  __/\/                                                ')
    disp( '/ / /`--´/____/\/  /_/ /   \__\// / /`--´|__/ /____/\/   PET-Partial Volume Effects correction toolbox ')
    disp(['\_\/     \____\/   \_\/         \_\/      \_\/\____\/    ','PETPVE12 ' num2str(r),'                   '])
    fprintf('\n');
end
%{
% optional welcome
if exist('r','var')
    disp( '            _                                                                      ')
    disp( ' _ __  ___ | |_  _ __ __   __ ___                                                  ')
    disp( '| ´_ \/ _ \|  _|| ´_ \\ \ / // _ \                                                 ')
    disp( '| |_)|  __/| |_ | |_)| \ V /   __/  PET-Partial Volume Effects correction toolbox  ')
    disp(['| ,__/\___||___|| ,__/  \_/  \___|  ','PETPVE12 ' num2str(r),'                    '])
    disp( '|_|             |_|                                                                ')
fprintf('\n');
end
%}

fig = spm_figure('GetWin','Interactive');
h0  = uimenu(fig,...
	'Label',	'PET-PVEc_Menu',...
	'Separator',	'on',...
	'Tag',		'PET-PVEc_12',...
	'HandleVisibility','on');
%------------------------------------------------------------------------
%------------------------------------------------------------------------
h1  = uimenu(h0,...
	'Label',	'Data representation',...
	'Separator',	'off',...
	'Tag',		'Check data quality',...
	'HandleVisibility','on');
h11  = uimenu(h1,...
	'Label',	'Display Functional Overlay',...
	'Separator',	'off',...
	'Tag',		'Display functional overlay',...
	'CallBack','geg_imageOverlay',...
	'HandleVisibility','on');
h12  = uimenu(h1,...
	'Label',	'Check sample homogeneity using covariance',...
	'Separator',	'off',...
	'Tag',		'Check sample homogeneity using covariance',...
	'CallBack','spm_jobman(''interactive'','''',''spm.tools.petpve.tools.check_cov'');',...
	'HandleVisibility','on');

%------------------------------------------------------------------------
h2  = uimenu(h0,...
	'Label',	'Pre-processing',...
	'Separator',	'off',...
	'Tag',		'Data preparation',...
	'HandleVisibility','on');
h21  = uimenu(h2,...
	'Label',	'Set image origin to the Center-Of-Mass',...
	'Separator',	'off',...
	'Tag',		'Set origin to the Center-Of-Mass',...
	'CallBack','geg_centerOfMass;',...
	'HandleVisibility','on');
h22  = uimenu(h2,...
	'Label',	'Segment & Skull-Strip T1 images',... 
	'Separator',	'off',...
	'Tag',		'Compute native GM/WM/CSF segments and use them to skull-strip images',...
	'CallBack','spm_jobman(''interactive'','''',''spm.tools.petpve.spatial.segment'');',...
	'HandleVisibility','on');
h23  = uimenu(h2,...
	'Label',	'Average PET frames',...
	'Separator',	'on',...
	'Tag',		'Average PET frames',...
	'CallBack','geg_PETframes_avg',...
	'HandleVisibility','on');
h24  = uimenu(h2,...
	'Label',	'Skull-Stripping using previously computed segments',...
	'Separator',	'on',...
	'Tag',		'Clean MRI images from non-brain tissue using precomputed tissue segments',...
	'CallBack','spm_jobman(''interactive'','''',''spm.tools.petpve.spatial.SkullStrip'');',...
	'HandleVisibility','on');
h25  = uimenu(h2,...
	'Label',	'Create DARTEL imported MRI tissue segments (rc*.nii)',...
	'Separator',	'off',...
	'Tag',		'Create the necessary tissue files to perform DARTEL alignment',...
	'CallBack','spm_jobman(''interactive'','''',''spm.tools.petpve.spatial.DrtlExport'');',...
	'HandleVisibility','on');
%------------------------------------------------------------------------
h3  = uimenu(h0,...
	'Label',	'Coregistration',...
	'Separator',	'off',...
	'Tag',		'Data alignment',...
	'HandleVisibility','on');
h31  = uimenu(h3,...
	'Label',	'Align PET-MRI images (Estimate)',...
	'Separator',	'off',...
	'Tag',		'Use SPM coregister to align PET and MRI data',...
	'CallBack','spm_jobman(''interactive'','''',''spm.tools.petpve.tools.coreg_estimate'');',...
	'HandleVisibility','on');
h32  = uimenu(h3,...
	'Label',	'Align PET-MRI images (Estimate & Reslice)',...
	'Separator',	'off',...
	'Tag',		'Use SPM coregister&reslice to align PET and MRI data',...
	'CallBack','spm_jobman(''interactive'','''',''spm.tools.petpve.tools.coreg_estwrite'');',...
	'HandleVisibility','on');
h33  = uimenu(h3,...
	'Label',	'Check PET-MRI alignment',...
	'Separator',	'on',...
	'Tag',		'Check PET-MRI alignment',...
	'CallBack','spm_jobman(''interactive'','''',''spm.tools.petpve.tools.ChkHdrs'');',...
	'HandleVisibility','on');
%------------------------------------------------------------------------
h4  = uimenu(h0,...
	'Label',	'Partial Volume Effects (PVE) correction',...
	'Separator',	'off',...
	'Tag',		'Processing tools',...
	'HandleVisibility','on');
h41  = uimenu(h4,...
	'Label',	'Partial Volume Effects (PVE) correction (MG)',...
	'Separator',	'off',...
	'Tag',		'Correct PET images for PVE using Muller-Gartner method',...
	'CallBack','spm_jobman(''interactive'','''',''spm.tools.petpve.spatial.PVEcorrection'');',...
	'HandleVisibility','on');
h42  = uimenu(h4,...
	'Label',	'Partial Volume Effects (PVE) correction (GTM)',...
	'Separator',	'off',...
	'Tag',		'Correct PET images for PVE using region-based Rousset method',...
	'CallBack','spm_jobman(''interactive'','''',''spm.tools.petpve.spatial.PVEcorrection2'');',...
	'HandleVisibility','on');
%------------------------------------------------------------------------
h5  = uimenu(h0,...
	'Label',	'Tools for the analysis of PET images',...
	'Separator',	'off',...
	'Tag',		'Analysis tools',...
	'HandleVisibility','on');
h51  = uimenu(h5,...
	'Label',	'Create binary masks from template atlas',...
	'Separator',	'on',...
	'Tag',		'Create mask/composite from atlas',...
	'CallBack','geg_composite_from_atlas',...
	'HandleVisibility','on');
h52  = uimenu(h5,...
	'Label',	'Create Atlas WM-ROIs',...
	'Separator',	'on',...
	'Tag',		'Parcellate WM regions from a template atlas',...
	'CallBack','spm_jobman(''interactive'','''',''spm.tools.petpve.spatial.WMrois'');',...
	'HandleVisibility','on');
h53  = uimenu(h5,...
	'Label',	'ROI/Atlas Estimations',...
	'Separator',	'on',...
	'Tag',		'ROI/Atlas Analysis tools',...
	'HandleVisibility','on');
h531  = uimenu(h53,...
	'Label',	'Mean values within ROIs (calculation in standard space)',...
	'Separator',	'on',...
	'Tag',		'Compute mean values inside a binary ROI for many subjects on standard space',...
	'CallBack','geg_calc_singleROImean',...
	'HandleVisibility','on');
h532  = uimenu(h53,...
	'Label',	'Mean values within all regions defined by an atlas (calculation in standard space)',...
	'Separator',	'off',...
	'Tag',		'Compute mean values from a template atlas for many subjects on standard space',...
	'CallBack','geg_calc_atlasROImeans',...
	'HandleVisibility','on');
h533  = uimenu(h53,...
	'Label',	'Mean values within ROIs (calculation in native space)',...
	'Separator',	'on',...
	'Tag',		'Compute mean values inside a binary ROI for many subjects on standard space',...
	'CallBack','geg_calc_singleROImean_native',...
	'HandleVisibility','on');
h534  = uimenu(h53,...
	'Label',	'Mean values within all regions defined by an atlas (calculation in native space)',...
	'Separator',	'off',...
	'Tag',		'Compute mean values from a template atlas for many subjects on native space',...
	'CallBack','geg_calc_atlasROImeans_native',...
	'HandleVisibility','on');
h54  = uimenu(h5,...
	'Label',	'PET intensity normalization',...
	'Separator',	'on',...
	'Tag',		'Perform intensity normalization of PET images',...
	'CallBack','spm_jobman(''interactive'','''',''spm.tools.petpve.tools.PETnorm'');',...
	'HandleVisibility','on');
%------------------------------------------------------------------------
h6  = uimenu(h0,...
	'Label',	'Print PETPVE12 debug information',...
	'Separator',	'on',...
	'Tag',		'Print debug information about versions and last error',...
	'CallBack','geg_petpve12_debug;',...
	'HandleVisibility','on');
%------------------------------------------------------------------------
h7  = uimenu(h0,...
	'Label',	'PETPVE12 Tools website',...
	'Separator',	'off',...
	'Tag',		'Launch petpve Tools site',...
	'CallBack',['set(gcbf,''Pointer'',''Watch''),',...
			'web(''https://multimodalneuroimaging.wordpress.com/software/'',''-browser'');',...
			'set(gcbf,''Pointer'',''Arrow'')'],...
	'HandleVisibility','on');
%------------------------------------------------------------------------
h8  = uimenu(h0,...
	'Label',	'Check for updates',...
	'Separator',	'off',...
	'Tag',		'Check for updates',...
	'CallBack','geg_petpve12_update(1);',...
	'HandleVisibility','on');
%------------------------------------------------------------------------
h9  = uimenu(h0,...
	'Label',	'PETPVE12 Manual (PDF)',...
	'Separator',	'off',...
	'Tag',		'Open PETPVE12 Manual',...
	'CallBack','try,open(fullfile(spm(''dir''),''toolbox'',''petpve12'',''help'',''PETPVE12_manual.pdf''));end',...
	'HandleVisibility','on');
